import { scaleOverclockMultiplier } from "../overclock-balance";

// Overclock upgrades are single-purchase and permanent; their effects follow the master and individual toggles.
//
// Every upgrade has a `kind`:
//   "flow"    - `effect` is a multiplier to Time Flow (how many seconds of game pass for every real second)
//   "score"   - scales a matching prestige currency gain with Time Flow
//   "gain"    - multiplies all prestige currency gains, stacking with Interest upgrades
//   "offline" - makes offline progress use Time Flow as well
//
// `checkRequirement` is evaluated live; an upgrade which has already been bought is never lost again.

const flowText = value => `Time Flow ${formatX(scaleOverclockMultiplier(value), 3, 3)}`;

export const overclockUpgrades = [
  // Row 1: Infinity
  {
    id: 1,
    name: "Running Start",
    kind: "flow",
    requirement: "None",
    checkRequirement: () => true,
    currency: () => Currency.antimatter,
    currencyName: "Antimatter",
    pluralizeCurrency: false,
    cost: 1e6,
    description: () => `${flowText(5)}. Everything in the game runs faster, not just your Dimensions`,
    effect: 5,
  },
  {
    id: 2,
    name: "Crunch Time",
    kind: "flow",
    requirement: "Reach Infinity",
    checkRequirement: () => PlayerProgress.infinityUnlocked(),
    currency: () => Currency.infinityPoints,
    currencyName: "Infinity Point",
    cost: 2,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 3,
    name: "Night Shift",
    kind: "offline",
    requirement: "Reach Infinity",
    checkRequirement: () => PlayerProgress.infinityUnlocked(),
    currency: () => Currency.infinityPoints,
    currencyName: "Infinity Point",
    cost: 10,
    description: "Apply 30% of the extra Time Flow speed while offline",
  },
  {
    id: 4,
    name: "Broken Clock",
    kind: "flow",
    requirement: "Break Infinity",
    checkRequirement: () => PlayerProgress.hasBroken() || PlayerProgress.eternityUnlocked(),
    currency: () => Currency.infinityPoints,
    currencyName: "Infinity Point",
    cost: 1e5,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 5,
    name: "Infinite Interest",
    kind: "score",
    requirement: "Break Infinity",
    checkRequirement: () => PlayerProgress.hasBroken() || PlayerProgress.eternityUnlocked(),
    currency: () => Currency.infinityPoints,
    currencyName: "Infinity Point",
    cost: 100,
    description: "Infinity Point gain gets 30% of the bonus from 5 times your Time Flow",
    effect: () => Overclock.interestMultiplier,
    formatEffect: value => formatX(value, 3, 3),
  },

  // Row 2: Eternity
  {
    id: 6,
    name: "Eternal Engine",
    kind: "flow",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 2,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 7,
    name: "Rush Hour",
    kind: "flow",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 100,
    description: () => `${flowText(2)} while you are inside any Challenge, Time Dilation, or a Celestial's Reality`,
    effect: () => (Overclock.isInChallenge ? 2 : 1),
    formatEffect: value => (value > 1 ? "Active" : "Inactive"),
  },
  {
    id: 8,
    name: "Muscle Memory",
    kind: "flow",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 1e6,
    description: () => `Time Flow +${formatPercents(0.003, 1)} for every Achievement you have ever had at once`,
    effect: () => 1 + player.overclock.maxAchievements / 100,
    formatEffect: value => formatX(value, 3, 3),
  },
  {
    id: 9,
    name: "Eternal Interest",
    kind: "score",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 1e6,
    description: "Eternity Point gain gets 30% of the bonus from 5 times your Time Flow",
    effect: () => Overclock.interestMultiplier,
    formatEffect: value => formatX(value, 3, 3),
  },
  {
    id: 10,
    name: "Dilated Pupils",
    kind: "flow",
    requirement: "Unlock Time Dilation",
    checkRequirement: () => PlayerProgress.dilationUnlocked() || PlayerProgress.realityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: new Decimal("1e1000"),
    description: () => flowText(1.5),
    effect: 1.5,
  },

  // Row 3: Reality and the Celestials
  {
    id: 11,
    name: "Reality Check",
    kind: "flow",
    requirement: "Reach Reality",
    checkRequirement: () => PlayerProgress.realityUnlocked(),
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 1,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 12,
    name: "Real Interest",
    kind: "score",
    requirement: "Reach Reality",
    checkRequirement: () => PlayerProgress.realityUnlocked(),
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 10,
    description: "Reality Machine gain gets 30% of the bonus from 5 times your Time Flow",
    effect: () => Overclock.interestMultiplier,
    formatEffect: value => formatX(value, 3, 3),
  },
  {
    id: 13,
    name: "Snowball",
    kind: "flow",
    requirement: "Reach Reality",
    checkRequirement: () => PlayerProgress.realityUnlocked(),
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 1e6,
    description: () => `Time Flow gains ${formatPercents(0.3)} of the bonus from ` +
      `${formatPercents(0.02)} compounding per enabled Overclock`,
    effect: () => Math.pow(1.02, OverclockUpgrades.enabledCount),
    formatEffect: value => formatX(value, 3, 3),
  },
  {
    id: 14,
    name: "Celestial Alignment",
    kind: "flow",
    requirement: "Unlock a Celestial",
    checkRequirement: () => player.overclock.maxCelestials > 0,
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 1e12,
    description: () => `Time Flow gains ${formatPercents(0.3)} of the bonus from ` +
      `${formatPercents(0.1)} compounding per unlocked Celestial`,
    effect: () => Math.pow(1.1, player.overclock.maxCelestials),
    formatEffect: value => formatX(value, 3, 3),
  },
  {
    id: 15,
    name: "Doomsday Clock",
    kind: "flow",
    requirement: "Unlock Pelle",
    checkRequirement: () => Pelle.isUnlocked || Pelle.isDoomed || PlayerProgress.endgameUnlocked(),
    currency: () => Currency.imaginaryMachines,
    currencyName: "Imaginary Machine",
    cost: 1e10,
    description: () => `${flowText(2)} while your Reality is Doomed`,
    effect: () => (Pelle.isDoomed ? 2 : 1),
    formatEffect: value => (value > 1 ? "Active" : "Inactive"),
  },

  // Row 4: Endgame and beyond
  {
    id: 16,
    name: "Encore",
    kind: "flow",
    requirement: "Reach Endgame",
    checkRequirement: () => PlayerProgress.endgameUnlocked(),
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: 1,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 17,
    name: "Broken Hourglass",
    kind: "flow",
    requirement: "Break Eternity",
    checkRequirement: () => PlayerProgress.endgameUnlocked() && player.break2,
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: 1e20,
    description: () => flowText(1.25),
    effect: 1.25,
  },
  {
    id: 18,
    name: "Celestial Interest",
    kind: "score",
    requirement: "Reach Celestial Infinity",
    checkRequirement: () => PlayerProgress.celestialInfinityUnlocked(),
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: new Decimal("1e300"),
    description: "Celestial Infinity Point and Celestial Eternity Point gain gets " +
      "30% of the bonus from 5 times your Time Flow",
    effect: () => Overclock.interestMultiplier,
    formatEffect: value => formatX(value, 3, 3),
  },
  {
    id: 19,
    name: "Divine Intervention",
    kind: "flow",
    requirement: "Reach Divinity",
    checkRequirement: () => PlayerProgress.divinityUnlocked(),
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: new Decimal("1e400"),
    description: () => flowText(1.25),
    effect: 1.25,
  },
  {
    id: 20,
    name: "Multiversal Time",
    kind: "flow",
    requirement: "Unlock a Universe",
    checkRequirement: () => Universes.areUnlocked,
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: new Decimal("1e1000"),
    description: () => flowText(1.25),
    effect: 1.25,
  },

  // Additional time accelerators and shared prestige bonuses
  {
    id: 21,
    name: "Afterburner",
    kind: "flow",
    requirement: "None",
    checkRequirement: () => true,
    currency: () => Currency.antimatter,
    currencyName: "Antimatter",
    pluralizeCurrency: false,
    cost: 1e50,
    description: () => flowText(2),
    effect: 2,
  },
  {
    id: 22,
    name: "Payday",
    kind: "gain",
    requirement: "Reach Infinity",
    checkRequirement: () => PlayerProgress.infinityUnlocked(),
    currency: () => Currency.infinityPoints,
    currencyName: "Infinity Point",
    cost: 25,
    description: () =>
      `Shared prestige gain bonus ${formatX(scaleOverclockMultiplier(5), 1, 1)}, stacking with Interest upgrades`,
    effect: 5,
  },
  {
    id: 23,
    name: "Eternal Overdrive",
    kind: "flow",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 1e3,
    description: () => flowText(2),
    effect: 2,
  },
  {
    id: 24,
    name: "Compound Dividends",
    kind: "gain",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 1e8,
    description: () =>
      `Shared prestige gain bonus ${formatX(scaleOverclockMultiplier(5), 1, 1)}, stacking with Interest upgrades`,
    effect: 5,
  },
  {
    id: 25,
    name: "Reality Accelerator",
    kind: "flow",
    requirement: "Reach Reality",
    checkRequirement: () => PlayerProgress.realityUnlocked(),
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 1e3,
    description: () => flowText(2),
    effect: 2,
  },
  {
    id: 26,
    name: "Machine Mint",
    kind: "gain",
    requirement: "Reach Reality",
    checkRequirement: () => PlayerProgress.realityUnlocked(),
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 1e5,
    description: () =>
      `Shared prestige gain bonus ${formatX(scaleOverclockMultiplier(5), 1, 1)}, stacking with Interest upgrades`,
    effect: 5,
  },
  {
    id: 27,
    name: "Cosmic Accelerator",
    kind: "flow",
    requirement: "Reach Endgame",
    checkRequirement: () => PlayerProgress.endgameUnlocked(),
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: 10,
    description: () => flowText(2),
    effect: 2,
  },
  {
    id: 28,
    name: "Cosmic Dividends",
    kind: "gain",
    requirement: "Reach Endgame",
    checkRequirement: () => PlayerProgress.endgameUnlocked(),
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: 1e10,
    description: () =>
      `Shared prestige gain bonus ${formatX(scaleOverclockMultiplier(5), 1, 1)}, stacking with Interest upgrades`,
    effect: 5,
  },
].map(config => {
  // Scale the extra benefit once, after evaluating any dynamic growth or condition.
  // Interest and offline bonuses are scaled in Overclock because they depend on total Time Flow.
  if (config.kind !== "flow" && config.kind !== "gain") return config;
  const effect = config.effect;
  return {
    ...config,
    effect: typeof effect === "function"
      ? () => scaleOverclockMultiplier(effect())
      : scaleOverclockMultiplier(effect)
  };
});
