// Overclock upgrades are single-purchase, permanent, and never have a level or an amount the player can pick.
//
// Every upgrade has a `kind`:
//   "flow"    - `effect` is a multiplier to Time Flow (how many seconds of game pass for every real second)
//   "score"   - multiplies a prestige currency gain by the current Time Flow; hooked up where that gain is calculated
//   "offline" - makes offline progress use Time Flow as well
//
// `checkRequirement` is evaluated live; an upgrade which has already been bought is never lost again.

const flowText = value => `Time Flow ${Number.isInteger(value) ? formatX(value) : formatX(value, 2, 2)}`;

export const overclockUpgrades = [
  // Row 1: Infinity
  {
    id: 1,
    name: "Running Start",
    kind: "flow",
    requirement: "None",
    checkRequirement: () => true,
    currency: () => Currency.antimatter,
    currencyName: "Antimatter",
    pluralizeCurrency: false,
    cost: 1e12,
    description: () => `${flowText(2)}. Everything in the game runs faster, not just your Dimensions`,
    effect: 2,
  },
  {
    id: 2,
    name: "Crunch Time",
    kind: "flow",
    requirement: "Reach Infinity",
    checkRequirement: () => PlayerProgress.infinityUnlocked(),
    currency: () => Currency.infinityPoints,
    currencyName: "Infinity Point",
    cost: 2,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 3,
    name: "Night Shift",
    kind: "offline",
    requirement: "Reach Infinity",
    checkRequirement: () => PlayerProgress.infinityUnlocked(),
    currency: () => Currency.infinityPoints,
    currencyName: "Infinity Point",
    cost: 10,
    description: "Time Flow also applies to time spent offline",
  },
  {
    id: 4,
    name: "Broken Clock",
    kind: "flow",
    requirement: "Break Infinity",
    checkRequirement: () => PlayerProgress.hasBroken() || PlayerProgress.eternityUnlocked(),
    currency: () => Currency.infinityPoints,
    currencyName: "Infinity Point",
    cost: 1e5,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 5,
    name: "Infinite Interest",
    kind: "score",
    requirement: "Break Infinity",
    checkRequirement: () => PlayerProgress.hasBroken() || PlayerProgress.eternityUnlocked(),
    currency: () => Currency.infinityPoints,
    currencyName: "Infinity Point",
    cost: 1e10,
    description: "Infinity Point gain is multiplied by your Time Flow",
    effect: () => Overclock.timeFlow,
    formatEffect: value => formatX(value, 2, 2),
  },

  // Row 2: Eternity
  {
    id: 6,
    name: "Eternal Engine",
    kind: "flow",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 2,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 7,
    name: "Rush Hour",
    kind: "flow",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 100,
    description: () => `${flowText(2)} while you are inside any Challenge, Time Dilation, or a Celestial's Reality`,
    effect: () => (Overclock.isInChallenge ? 2 : 1),
    formatEffect: value => (value > 1 ? "Active" : "Inactive"),
  },
  {
    id: 8,
    name: "Muscle Memory",
    kind: "flow",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 1e6,
    description: () => `Time Flow +${formatPercents(0.01)} for every Achievement you have ever had at once`,
    effect: () => 1 + player.overclock.maxAchievements / 100,
    formatEffect: value => formatX(value, 2, 2),
  },
  {
    id: 9,
    name: "Eternal Interest",
    kind: "score",
    requirement: "Reach Eternity",
    checkRequirement: () => PlayerProgress.eternityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: 1e30,
    description: "Eternity Point gain is multiplied by your Time Flow",
    effect: () => Overclock.timeFlow,
    formatEffect: value => formatX(value, 2, 2),
  },
  {
    id: 10,
    name: "Dilated Pupils",
    kind: "flow",
    requirement: "Unlock Time Dilation",
    checkRequirement: () => PlayerProgress.dilationUnlocked() || PlayerProgress.realityUnlocked(),
    currency: () => Currency.eternityPoints,
    currencyName: "Eternity Point",
    cost: new Decimal("1e1000"),
    description: () => flowText(1.5),
    effect: 1.5,
  },

  // Row 3: Reality and the Celestials
  {
    id: 11,
    name: "Reality Check",
    kind: "flow",
    requirement: "Reach Reality",
    checkRequirement: () => PlayerProgress.realityUnlocked(),
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 1,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 12,
    name: "Real Interest",
    kind: "score",
    requirement: "Reach Reality",
    checkRequirement: () => PlayerProgress.realityUnlocked(),
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 100,
    description: "Reality Machine gain is multiplied by your Time Flow",
    effect: () => Overclock.timeFlow,
    formatEffect: value => formatX(value, 2, 2),
  },
  {
    id: 13,
    name: "Snowball",
    kind: "flow",
    requirement: "Reach Reality",
    checkRequirement: () => PlayerProgress.realityUnlocked(),
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 1e6,
    description: () => `Time Flow +${formatPercents(0.02)} (compounding) for every Overclock you own`,
    effect: () => Math.pow(1.02, OverclockUpgrades.boughtCount),
    formatEffect: value => formatX(value, 2, 2),
  },
  {
    id: 14,
    name: "Celestial Alignment",
    kind: "flow",
    requirement: "Unlock a Celestial",
    checkRequirement: () => player.overclock.maxCelestials > 0,
    currency: () => Currency.realityMachines,
    currencyName: "Reality Machine",
    cost: 1e12,
    description: () => `Time Flow +${formatPercents(0.1)} (compounding) for every Celestial you have ever unlocked`,
    effect: () => Math.pow(1.1, player.overclock.maxCelestials),
    formatEffect: value => formatX(value, 2, 2),
  },
  {
    id: 15,
    name: "Doomsday Clock",
    kind: "flow",
    requirement: "Unlock Pelle",
    checkRequirement: () => Pelle.isUnlocked || Pelle.isDoomed || PlayerProgress.endgameUnlocked(),
    currency: () => Currency.imaginaryMachines,
    currencyName: "Imaginary Machine",
    cost: 1e10,
    description: () => `${flowText(2)} while your Reality is Doomed`,
    effect: () => (Pelle.isDoomed ? 2 : 1),
    formatEffect: value => (value > 1 ? "Active" : "Inactive"),
  },

  // Row 4: Endgame and beyond
  {
    id: 16,
    name: "Encore",
    kind: "flow",
    requirement: "Reach Endgame",
    checkRequirement: () => PlayerProgress.endgameUnlocked(),
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: 1,
    description: () => flowText(1.5),
    effect: 1.5,
  },
  {
    id: 17,
    name: "Broken Hourglass",
    kind: "flow",
    requirement: "Break Eternity",
    checkRequirement: () => PlayerProgress.endgameUnlocked() && player.break2,
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: 1e20,
    description: () => flowText(1.25),
    effect: 1.25,
  },
  {
    id: 18,
    name: "Celestial Interest",
    kind: "score",
    requirement: "Reach Celestial Infinity",
    checkRequirement: () => PlayerProgress.celestialInfinityUnlocked(),
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: new Decimal("1e300"),
    description: "Celestial Infinity Point and Celestial Eternity Point gain is multiplied by your Time Flow",
    effect: () => Overclock.timeFlow,
    formatEffect: value => formatX(value, 2, 2),
  },
  {
    id: 19,
    name: "Divine Intervention",
    kind: "flow",
    requirement: "Reach Divinity",
    checkRequirement: () => PlayerProgress.divinityUnlocked(),
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: new Decimal("1e400"),
    description: () => flowText(1.25),
    effect: 1.25,
  },
  {
    id: 20,
    name: "Multiversal Time",
    kind: "flow",
    requirement: "Unlock a Universe",
    checkRequirement: () => Universes.areUnlocked,
    currency: () => Currency.celestialPoints,
    currencyName: "Celestial Point",
    cost: new Decimal("1e1000"),
    description: () => flowText(1.25),
    effect: 1.25,
  },
];
